language: go
sudo: false
go:
  - 1.12.x

before_install:
  - go get -t -v ./...

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm -f coverage.txt


before_deploy:
  - rm -f coverage.txt
  - sed -i "s/version = \"dev\"/version = \"${TRAVIS_BRANCH}\"/" main.go

deploy:
  - provider: script
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
